"""
Pydantic schemas for request/response models.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class InvestigationStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONFLICTING = "CONFLICTING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


# ─── Document Schemas ──────────────────────────────────────────────────────────

class DocumentUploadResponse(BaseModel):
    success: bool
    filename: str
    document_id: str
    pages: int
    chunks: int
    ocr_used: bool = False
    message: str


class DocumentInfo(BaseModel):
    document_id: str
    filename: str
    upload_time: str
    pages: int
    chunks: int
    file_type: str
    ocr_used: bool = False


class DocumentListResponse(BaseModel):
    documents: List[DocumentInfo]
    total: int


class DeleteDocumentResponse(BaseModel):
    success: bool
    message: str
    document_id: str


# ─── Evidence & Source Schemas ─────────────────────────────────────────────────

class EvidenceItem(BaseModel):
    document: str
    page: Optional[int] = None
    quote: str
    chunk_index: int
    section: Optional[str] = None
    source_type: str = "unknown"
    similarity_score: float = 0.0


class SourceCitation(BaseModel):
    document: str
    page: Optional[int] = None
    excerpt: str = ""
    relevance: float = 0.0
    relevant_text: str = ""  # kept for backward compatibility
    similarity_score: float = 0.0  # kept for backward compatibility
    chunk_index: int = 0

    def model_post_init(self, __context: Any) -> None:
        if not self.excerpt and self.relevant_text:
            self.excerpt = self.relevant_text
        if not self.relevant_text and self.excerpt:
            self.relevant_text = self.excerpt
        if self.relevance == 0.0 and self.similarity_score != 0.0:
            self.relevance = self.similarity_score
        if self.similarity_score == 0.0 and self.relevance != 0.0:
            self.similarity_score = self.relevance


# ─── Conflict Schemas ──────────────────────────────────────────────────────────

class ConflictDetail(BaseModel):
    type: str  # numeric_conflict, semantic_conflict, direct_contradiction
    topic: str
    description: str
    source_a: Dict[str, Any]
    source_b: Dict[str, Any]
    why_it_matters: Optional[str] = (
        "The available documents disagree, so the system cannot establish a single definitive answer."
    )


# ─── Question & Answer Schemas ─────────────────────────────────────────────────

class QuestionRequest(BaseModel):
    question: str = Field(..., min_length=3, max_length=2000)


class LLMAnswerOutput(BaseModel):
    """Structured JSON schema generated by the LLM."""
    answer: str
    status: InvestigationStatus
    confidence: ConfidenceLevel
    uncertainty: Optional[str] = None
    evidence_points: List[str] = []
    source_ids: List[int] = []


class InvestigationResult(BaseModel):
    investigation_id: str
    question: str
    answer: str
    status: InvestigationStatus
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    confidence_level: ConfidenceLevel
    confidence_explanation: str = ""
    uncertainty: Optional[str] = None
    evidence_points: List[str] = []
    evidence: List[EvidenceItem] = []
    conflicts: List[ConflictDetail] = []
    sources: List[SourceCitation] = []
    timestamp: str
    processing_time_ms: int = 0


# ─── Investigation History Schemas ─────────────────────────────────────────────

class InvestigationSummary(BaseModel):
    investigation_id: str
    question: str
    status: InvestigationStatus
    confidence: float
    timestamp: str


class InvestigationHistoryResponse(BaseModel):
    investigations: List[InvestigationSummary]
    total: int


# ─── Health Check ──────────────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str
    version: str
    chroma_status: str
    embedding_model: str
    llm_model: str
    documents_indexed: int
